---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: rtdash
  name: rtdash
spec:
  containers:
  - image: tpadevopsacr.azurecr.io/rtdashs:a0432b2__linux_amd64
    imagePullPolicy: Always
    name: rtdash
    ports:
    - containerPort: 3000
  